In [9]:
import pickle
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
enron_data = pickle.load(open("final_project/final_project_dataset.pkl", "rb"))

In [13]:
enron_data = pd.DataFrame.from_dict(enron_data)
enron_data.replace(to_replace='NaN', value=np.nan, inplace=True)
enron_data
#enron_data.keys()

,METTS MARK,BAXTER JOHN C,ELLIOTT STEVEN,CORDES WILLIAM R,HANNON KEVIN P,MORDAUNT KRISTINA M,MEYER ROCKFORD G,MCMAHON JEFFREY,HAEDICKE MARK E,PIPER GREGORY F,...,SAVAGE FRANK,IZZO LAWRENCE L,TILNEY ELIZABETH A,MARTIN AMANDA K,BUY RICHARD B,GRAMM WENDY L,CAUSEY RICHARD A,TAYLOR MITCHELL S,DONAHUE JR JEFFREY M,GLISAN JR BEN F
bonus,600000,1200000,350000,NaN,1500000,325000,NaN,2600000,1150000,400000,...,NaN,NaN,300000,NaN,900000,NaN,1000000,600000,800000,600000
deferral_payments,NaN,1295738,NaN,NaN,NaN,NaN,1848227,NaN,2157527,1130036,...,NaN,NaN,NaN,85430,649584,NaN,NaN,227449,NaN,NaN
deferred_income,NaN,-1386055,-400729,NaN,-3117011,NaN,NaN,NaN,-934484,-33333,...,-121284,NaN,-575000,NaN,-694862,NaN,-235000,NaN,-300000,NaN
director_fees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,125034,NaN,NaN,NaN,NaN,119292,NaN,NaN,NaN,NaN
email_address,mark.metts@enron.com,NaN,steven.elliott@enron.com,bill.cordes@enron.com,kevin.hannon@enron.com,kristina.mordaunt@enron.com,rockford.meyer@enron.com,jeffrey.mcmahon@enron.com,mark.haedicke@enron.com,greg.piper@enron.com,...,NaN,larry.izzo@enron.com,elizabeth.tilney@enron.com,a..martin@enron.com,rick.buy@enron.com,NaN,richard.causey@enron.com,mitchell.taylor@enron.com,jeff.donahue@enron.com,ben.glisan@enron.com
exercised_stock_options,NaN,6680544,4890344,651850,5538001,NaN,493489,1104054,608750,880290,...,NaN,2165172,591250,2070306,2542813,NaN,NaN,3181250,765920,384728
expenses,94299,11200,78552,NaN,34039,35018,NaN,137108,76169,43057,...,NaN,28093,NaN,8211,NaN,NaN,30674,NaN,96268,125978
from_messages,29,NaN,NaN,12,32,NaN,28,48,1941,222,...,NaN,19,19,230,1053,NaN,49,29,22,16
from_poi_to_this_person,38,NaN,NaN,10,32,NaN,0,58,180,61,...,NaN,28,10,8,156,NaN,58,0,188,52
from_this_person_to_poi,1,NaN,NaN,0,21,NaN,0,26,61,48,...,NaN,5,11,0,71,NaN,12,0,11,6
loan_advances,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
long_term_incentive,NaN,1586055,NaN,NaN,1617011,NaN,NaN,694862,983346,NaN,...,NaN,312500,275000,5145434,769862,NaN,350000,NaN,NaN,71023
other,1740,2660303,12961,NaN,11350,1411,NaN,297353,52382,778,...,NaN,1553729,152055,2818454,400572,NaN,307895,NaN,891,200308
poi,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
restricted_stock,585062,3942714,1788391,386335,853064,208510,462384,558801,524169,409554,...,NaN,3654808,576792,NaN,901657,NaN,2502063,563798,315068,393818
restricted_stock_deferred,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-329825,-409554,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary,365788,267102,170941,NaN,243293,267093,NaN,370448,374125,197091,...,NaN,85274,247338,349487,330546,NaN,415189,265214,278601,274975
shared_receipt_with_poi,702,NaN,NaN,58,1035,NaN,22,2228,1847,742,...,NaN,437,379,477,2333,NaN,1585,300,772,874
to_messages,807,NaN,NaN,764,1045,NaN,232,2355,4009,1238,...,NaN,496,460,1522,3523,NaN,1892,533,865,873
total_payments,1061827,5634343,211725,NaN,288682,628522,1848227,4099771,3859065,1737629,...,3750,1979596,399393,8407016,2355702,119292,1868758,1092663,875760,1272284
total_stock_value,585062,10623258,6678735,1038185,6391065,208510,955873,1662855,803094,880290,...,NaN,5819980,1168042,2070306,3444470,NaN,2502063,3745048,1080988,778546

In [15]:
print ("Number of Data Points (People):",len(enron_data))
print ("Number of features: ", len(enron_data['BUY RICHARD B']))

Number of Data Points (People): 21
Number of features:  21

In [16]:
count = 0
for point in enron_data.keys():
    if (enron_data[point]['poi'] == True):
        count +=1
count

18

In [18]:
poi_names = open("final_project/poi_names.txt", "r")
pcount=0
lines = poi_names.readlines()
for line in lines:
    if line[0] == "(":
        pcount+=1
pcount

35

In [19]:
print (enron_data["PRENTICE JAMES"]["total_stock_value"])

1095040

In [20]:
scount = 0
ecount = 0
tpcount = 0
for point in enron_data.keys():
    if (enron_data[point]['salary'] != 'NaN'):
        scount +=1
    if (enron_data[point]['email_address'] != 'NaN'):
        ecount +=1
    if (enron_data[point]['total_payments'] == 'NaN'):
        tpcount +=1
print (scount)
print (ecount)
print (tpcount)

146
146
0

In [21]:
21/146

0.14383561643835616

In [22]:
ppcount = 0
for point in enron_data.keys():
    if (enron_data[point]['poi']== True and enron_data[point]['total_payments'] == 'NaN'):
        ppcount +=1
ppcount

0